name: antarctica-today
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipython~=7.29
  - numpy=1.21
  - netcdf4~=1.5
  - pillow~=8.3
  - gdal~=3.3
  - matplotlib-base~=3.4
  - pyproj~=3.2
  - pandas~=1.3
  - geopandas~=0.10
  - cartopy~=0.20
  - statsmodels~=0.13
  - shapely==1.7.1
  - pip
